version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/start
    volumes:
      - .:/app:cached
      - bundle:/.bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - postgres
    tmpfs:
      - /tmp
  postgres:
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  node_modules:
  bundle:
  db:
  rails_cache:
  packs:
